### ISSUE TITLE
svg4everybody

### ISSUE THREAD

**Issue by Jakobud** [frexy/svg-sprite-polyfill#1]
What is the difference between this and svg4everybody.js?

**Comment by CesarRotela** [comment]
+1

**Comment by Jakobud** [comment]
Okay so reading more indepth into this, svg4everybody uses data-img attributes in your SVG elements to  replace the svg tags with <img> tags that point to PNG fallback images.

This polyfill injects your external SVG inline into your HTML so that you can properly use and manipulate SVG sprites. This polyfill also copies your <symbol> viewBox attributes to your SVG in your html.

Is that right?

**Comment by mintran** [comment]
@Jakobud Yes you're right. The main purpose of polyfill.js is forcing IE/Chrome/Safari to treat svg symbol served via &lt;use&gt; as inline SVG for the shake of CSS styling.
